repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
        additional_dependencies: [pep8-naming]
        args: ["--max-line-length=200"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
